name: Ruby

on:
  - push
  - pull_request

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        ruby: [3.3, head]
    steps:
      - uses: actions/checkout@v4
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true
      - name: Run tests
        run: bundle exec rspec

  license_checks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: "3.3"
          bundler-cache: true
      - name: Check licenses
        run: bundle exec license_finder

  summary:
    name: CI Summary
    runs-on: ubuntu-latest
    needs:
      - test
      - license_checks
    if: always()

    steps:
      - name: Successful builds?
        run: |
          if ${{ needs.test.result != 'success' }}; then exit 1; fi
          if ${{ needs.license_checks.result != 'success' }}; then exit 1; fi
